services:
  # Backend API service
  - type: web
    name: nextrides-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT

  # Static site configuration for the frontend
  - type: static
    name: nextride-frontend
    env: static
    buildCommand: cd frontend && yarn install && yarn build
    staticPublishPath: frontend/build
    routes:
      # Rewrites all untracked routes to index.html for React Router
      - source: /*
        destination: /index.html
        type: rewrite

